#!/usr/bin/env bash
set -e

create_links_in_dir_recursively() {
    local base_dir="$PWD/$1"
    local target_dir="$2"

    for dir in $(find "$base_dir/" -type d); do
        mkdir -p "$HOME/$target_dir${dir#$base_dir}"
        for file in $(find "$dir" -maxdepth 1 -type f); do
            ln -sf "$file" "$HOME/$target_dir${file#$base_dir}"
        done
    done
}

ln -sf "$PWD/zshrc" "$HOME/.zshrc"
ln -sf "$PWD/gitconfig" "$HOME/.gitconfig"
ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"

mkdir -p "$HOME/bin/"
for file in $(find "$PWD/bin" -type f); do
    ln -sf "$file" "$HOME/bin"
done

create_links_in_dir_recursively "config" ".config"
ln -sf "$PWD/config/alacritty.yml" "$HOME/.config/alacritty.yml"
ln -sf "$PWD/config/electron-flags.conf" "$HOME/.config/electron-flags.conf"
ln -sf "$PWD/config/starship.toml" "$HOME/.config/starship.toml"

create_links_in_dir_recursively "logseq" ".logseq"
