local o = vim.opt

vim.g.mapleader = " "
vim.g.maplocalleader = ","
vim.g.netrw_banner = false

-- o.laststatus = 0
o.backup = false
o.clipboard = "unnamedplus"
o.cmdheight = 1
o.colorcolumn = "99999"
o.completeopt = { "menuone", "noselect" }
o.conceallevel = 0
o.fileencoding = "utf-8"
o.foldmethod = "manual"
o.foldexpr = ""
o.guifont = "JetBrains Mono Nerd Font:h17"
o.hidden = true
o.hlsearch = true
o.ignorecase = true
o.mouse = "a"
o.pumheight = 10
o.showmode = false
o.smartcase = true
o.smartindent = true
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.termguicolors = true
-- o.timeoutlen = 100
o.title = true
o.undofile = true
o.updatetime = 300
o.writebackup = false
o.expandtab = true
o.shiftwidth = 2
o.tabstop = 2
o.cursorline = true
o.number = true
o.relativenumber = true
o.numberwidth = 4
o.signcolumn = "yes"
o.wrap = false
o.spell = false
o.spelllang = "en"
o.scrolloff = 8
o.sidescrolloff = 8
