#!/bin/sh
# Smirnov-O <ss2316544@gmail.com>
# BSPWM config file

###== Functions
A() {  # AutoStart
  if ! pgrep $1
     then $@& fi
}
C() {  # Config
    bspc config $@
}
R() {  # Set rule
    bspc rule -a $@
}

#== Autostart
A feh --randomize --bg-scale ~/Pictures/wallp &
xautolock -time 5 -locker "slock" &
A sxhkd -c ~/.config/bspwm/sxhkd &
~/.config/bspwm/polybar/bar.sh &
A picom -b &

#== BSPWM

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# General
C border_width          2
C window_gap            2
C split_ratio           0.50
C borderless_monocle    true
C gapless_monocle       true
C single_monocle        true
C focus_follows_pointer true

# Colors
C normal_border_color  "#090909"
C active_border_color  "#1F2324"
C focused_border_color "#008DCD"
C urgent_border_color  "#FF6C6B"

#== BSPWM Rules
R kitty           desktop='^1' focus=on  follow=on
R Google-chrome   desktop='^2' focus=on  follow=on
R Code            desktop='^3' focus=on  follow=on
R Simplenote      desktop='^4' focus=on  follow=on
R Nemo            desktop='^5' focus=on  follow=on
R Zathura         desktop='^5' focus=on  follow=on state=tiled
R discord         desktop='^6' focus=on  follow=off
R TelegramDesktop desktop='^6' focus=off follow=on
R KeePassXC       desktop='^7' focus=on  follow=on
