#!/bin/bash
sxhkd -c ~/.config/berry/sxhkdrc &
picom -b &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
setxkbmap "us,ru,ua" ",winkeys" "grp:alt_shift_toggle" -option "ctrl:nocaps" &
~/.config/berry/polybar/bar.sh &
nitrogen --restore &

berryc border_width       1
berryc inner_border_width 1 
berryc title_height       0
berryc top_gap            0 

berryc focus_color         073642
berryc unfocus_color       002b36
berryc inner_focus_color   268bd2
berryc inner_unfocus_color 002b36
berryc text_focus_color    ffffff
berryc text_unfocus_color  efefef

berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Jetbrains Mono"
