[tools]
usage = "latest"
bun = "latest"
node = "lts"
gleam = "latest"
go = "latest"
golangci-lint = "latest"
hledger = "latest"
lua-language-server = "latest"
shellcheck = "latest"
shfmt = "latest"

[settings]
npm.package_manager = "bun"
go_set_gobin = false
go_set_gopath = false
go_set_goroot = true
