[tools]
bun = "latest"
flyctl = "latest"
gleam = "latest"
go = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
lua-language-server = "latest"
node = "lts"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"

[settings]
experimental = true
go_set_gobin = false
go_set_gopath = false
go_set_goroot = false
