[tools]
usage = "latest"
shfmt = "latest"
shellcheck = "latest"
node = "lts"
golangci-lint-langserver = "latest"
golangci-lint = "latest"
go = "latest"
gleam = "latest"
bun = "latest"

[settings]
experimental = true
go_set_gobin = false
go_set_gopath = false
go_set_goroot = false
