[tools]
usage = "latest"
bun = "latest"
gleam = "latest"
go = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
hledger = "latest"
lua-language-server = "3.16.4"
node = "lts"
shellcheck = "latest"

[settings]
npm.package_manager = "bun"
go_set_gobin = false
go_set_gopath = false
go_set_goroot = false
